### ISSUE TITLE
New MTL papers from our group

### ISSUE THREAD

**Issue by zhanglijun95** [Manchery/awesome-multi-task-learning#2]
Hi there,

We're a [MLSys group](https://guanh01.github.io/) working on multi-task learning at the University of Massachusetts Amherst. Recently we have some new works completed. Would you mind taking a look at these papers and adding them to your repo list? Thank you!
1. [Rethinking hard-parameter sharing in multi-domain learning](https://arxiv.org/pdf/2107.11359.pdf), accepted by ICME 2022 (acceptance rate 29%).
2. [AutoMTL: A Programming Framework for Automated Multi-Task Learning](https://arxiv.org/pdf/2110.13076.pdf). A NAS-based MTL infrastructure. 
3. [A Tree-Structured Multi-Task Model Recommender](https://arxiv.org/pdf/2203.05092.pdf), accepted by AutoML-Conf 2022 (acceptance rate 19.2%).

Best,
Lijun Zhang

**Comment by Manchery** [comment]
Hi, Lijun. Thank you very much for your awesome works and contribution!
Unfortunately, I am currently busy with my undergraduate thesis, so I will read your papers and consider how to add them to my taxonomy within a week.

**Comment by zhanglijun95** [comment]
No problem. Take your time! Good luck with your thesis.

**Comment by Manchery** [comment]
Hi, I have updated the repo to include three papers mentioned above. I will close this issue if there is no further problem.
