### ISSUE TITLE
推荐

### ISSUE THREAD

**Issue by HiNLP** [Manchery/awesome-multi-task-learning#3]
大佬好，毛遂自荐[bert4torch](https://github.com/Tongjilibo/bert4torch)这个仓库，是参考苏神的bert4keras的pytorch实现，目前已有500+star，欢迎试用和star

**Comment by Manchery** [comment]
不好意思，这个库似乎跟多任务学习没有明显的关系

Sorry, this repo (bert4torch) seems to have no obvious relationship with multi-task learning
