### ISSUE TITLE
Add a new EMNLP paper

### ISSUE THREAD

**Issue by yftah89** [Manchery/awesome-multi-task-learning#9]
Thank you for creating this helpful repo. 
Can you please add the recent EMNLP (2024) paper - "Layer by Layer: Uncovering Where Multi-Task Learning Happens in
Instruction-Tuned Large Language Models". We believe it's highly relevant for this repo. 
This is its most updated version - https://aclanthology.org/2024.emnlp-main.847.pdf

**Comment by Manchery** [comment]
Thanks for your contribution. I find this paper really interesting and have included it in the paper list. Feel free to make a PR if any adjustment is needed

**Comment by yftah89** [comment]
Thank you for your quick response :)
